version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"  # Expose Redis port
    networks:
      - my-network

  app:
    build: .  # Specify the path to your Dockerfile
    container_name: autify-app
    ports:
      - "3000:3000"  # Assuming your app runs on port 3000
    depends_on:
      - redis
    environment:
      REDIS_HOST: my-redis  # Use the Redis container name as the host
      REDIS_PORT: 6379
    networks:
      - my-network
    volumes:
      - resources_data:/app/resources

networks:
  my-network:
    driver: bridge

volumes:
  resources_data:
